-- 코드를 입력하세요
SELECT 
  BOARD.TITLE,
  BOARD.BOARD_ID,
  REPLY.REPLY_ID,
  REPLY.WRITER_ID,
  REPLY.CONTENTS,
  DATE_FORMAT(REPLY.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD
  -- 두 테이블을 활용하기에 BOARD_ID 기반 INNER JOIN
  INNER JOIN USED_GOODS_REPLY AS REPLY 
    ON REPLY.BOARD_ID = BOARD.BOARD_ID
-- 날짜가 2022년 10월에 작성된 게시글만 필터링
WHERE DATE_FORMAT(BOARD.CREATED_DATE, "%Y-%m") = '2022-10' 
-- 댓글 작성일을 기준으로 오름차순, 게시글 제목을 기준으로 오름차순
ORDER BY 
  CREATED_DATE ASC,
  TITLE ASC